// AUTO-GENERATED by: npx tsx scripts/measure-region-baselines.ts
// Run `npm run measure:baselines` to update after adding/removing sources.
// Last measured: not yet measured — these are initial estimates
export const REGION_BASELINES: Record<string, number> = {
  'us': 80,
  'middle-east': 50,
  'europe-russia': 40,
  'latam': 20,
  'asia': 20,
  'africa': 20,
  'all': 250,
};
export const BASELINES_MEASURED_AT = 'initial-estimates';
