// AUTO-GENERATED by: npx tsx scripts/measure-region-baselines.ts
// Run `npm run measure:baselines` to update after adding/removing sources.
// Last measured: 2026-02-28T08:58:18.999Z
// Based on 12 complete 6h buckets (2026-02-25T06:00:00.000Z → 2026-02-28T00:00:00.000Z)
export const REGION_BASELINES: Record<string, number> = {
  'us': 68,
  'latam': 20,
  'middle-east': 28,
  'europe-russia': 44,
  'asia': 20,
  'africa': 20,
  'all': 206,
};
export const BASELINES_MEASURED_AT = '2026-02-28T08:58:18.999Z';
